### ISSUE TITLE
failed back-merge

### ISSUE THREAD

**Issue by leonidgorbachev** [lilSpeedwagon/Simple-UUIDs-Microservice#1]
Please consider to fix failed merge in index.js

**Comment by leonidgorbachev** [comment]
@lilSpeedwagon

**Comment by lilSpeedwagon** [comment]
@leonidgorbachev thank you for the comment.
I had resolved the merge conflict on my machine, but for some reasons, these insertions came into the origin and I haven't noticed it.
Fixed.
